//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateSheet
    {
        public int CourseId { get; set; }
        public int TeacherId { get; set; }
        public int SectionId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AddSection AddSection { get; set; }
        public virtual AddTeacher AddTeacher { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
