USE [master]
GO

/****** Object:  Database [Final]    Script Date: 5/2/2019 9:54:28 PM ******/
CREATE DATABASE [Final]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Final', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Final.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Final_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Final_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Final] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Final].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Final] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Final] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Final] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Final] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Final] SET ARITHABORT OFF 
GO

ALTER DATABASE [Final] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Final] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Final] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Final] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Final] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Final] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Final] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Final] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Final] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Final] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Final] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Final] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Final] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Final] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Final] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Final] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Final] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Final] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Final] SET  MULTI_USER 
GO

ALTER DATABASE [Final] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Final] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Final] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Final] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Final] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Final] SET  READ_WRITE 
GO


